name: CI

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - "**"

concurrency:
  group: ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  dependency-safety:
    name: Dependency Safety
    runs-on: ubuntu-latest
    container: debian:latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version-file: 'package.json'
          cache: npm

      - run: npm ci --ignore-scripts
      - run: npm audit signatures
      - run: npm audit --audit-level=high

  checks:
    name: Lint and Tests
    runs-on: ubuntu-latest
    container: debian:latest
    needs: dependency-safety
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version-file: 'package.json'
          cache: npm

      - run: npm ci
      - run: npm run style:dry
      - run: npm test
